### PR TITLE
[TeamView] Fix permissions bug #185

### LINKED ISSUE #185: TeamView: permissions bug
image

When I look at the team-view, even when not logged in, I can see the `add-team` and `edit custom styles` buttons. These probably need a `v-if="canEdit"` somewhere...

### PR DESCRIPTION
**Pull request by davemecha**
Fix permissions bug #185

* add translations for button
* show add subteam button and custom styles button only for users with edit permissions
* fix markup (no button/chip) as child of ul
* show subteams headline only when subteams are present or for users with edit permissions

### CODE REVIEW

File: src/views/Team/Outlet.vue [hunk 1]
```diff
@@ -112,30 +112,32 @@
...
-                  >
-                    <ion-chip outline>
-                      <avatar withName :profile="t" size="1.5em" />
-                    </ion-chip>
-                  </router-link>
-                </li>
-
-                <ion-chip outline>
+              <div>
+                <h2 v-if="subteams?.length || canEdit">
```
Comment (gnunicorn) [inline src/views/Team/Outlet.vue:116]: isn't an empty array falsy in vue - in any case it is computed and 'soft' guaranteed to be an array so `?` is unneessary? Either way, I consider it better style to have any non-trivial checks outsourced into a `computed` on the component for legibility.

**Review by gnunicorn — APPROVED** [review]
Nice, minor style nitpick, please fix and feel free to merge without another review!

File: src/views/Team/Outlet.vue (hunk 1 above)
Comment (davemecha) [reply src/views/Team/Outlet.vue:116]: AFAIK an empty array is not falsy in vue. (same as with javascript). The `?` may be unnecessary, but it's more failsafe to use it. ;)

Also personally I like simple (but non-trivial) checks more directly in the template. The code is faster to read because I see directly what happens. But I'll change that to your preferences.
